version: 1.2
workflows:
  - name: "terra-upsert"
    subclass: WDL
    primaryDescriptorPath: /wdls/terra_upsert.wdl

  - name: "10X-import"
    subclass: WDL
    primaryDescriptorPath: /wdls/10x_imports.wdl

  - name: "SHARE-seq-import"
    subclass: WDL
    primaryDescriptorPath: /wdls/shareseq_imports.wdl

  - name: "ChIP-seq-import"
    subclass: WDL
    primaryDescriptorPath: /wdls/chipseq_imports.wdl

  - name: "ChIP-seq"
    subclass: WDL
    primaryDescriptorPath: /wdls/chipseq.wdl
    
  - name: "CNV"
    subclass: WDL
    primaryDescriptorPath: /wdls/cnv.wdl