substitutions:
  _ENV: dev
  _DELETION_POLICY: delete
  _REPO_OWNER: broadinstitute
  _GCR_REGISTRY: us.gcr.io
  _BUCKETS_REGION: us-east1
  _ARTIFACT_REGISTRY: us-east1-docker.pkg.dev
  _REPOSITORY: lims-tools

steps:
- name: gcr.io/cloud-builders/gcloud
  id: deploy-functions
  entrypoint: ./deploy.sh
  env:
  - VERSION=git-${SHORT_SHA}
  - BUCKETS_REGION=${_BUCKETS_REGION}
  args:
  - ${_ENV}
  - ${_DELETION_POLICY}
  timeout: 800s

# BCL Convert
- id: 'download-bcl-convert'
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - "-c"
    - |
      echo "Downloading bcl-convert RPM..."
      gsutil cp gs://broad-epi_cloudbuild/bcl-convert-4.3.6-2.el7.x86_64.rpm bcl-convert.rpm
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  env:
  - 'docker=dockerfiles/bcl_convert.dockerfile'
  - 'image=${_ARTIFACT_REGISTRY}/${PROJECT_ID}/${_REPOSITORY}/bcl_convert:latest'
  script: |
    #!/usr/bin/env bash
    if docker pull ${image}; then
      docker build -t ${image} --cache-from ${image} -f ${docker} .
    else
      docker build -t ${image} -f ${docker} .
    fi
    if [ $? -ne 0 ]; then
      # Notify Slack on build failure
      # curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Build failed for ${image} in ${_REPOSITORY}\"}' ${_SLACK_WEBHOOK_URL}
      exit 1
    fi
    docker push ${image}
  waitFor: ['download-bcl-convert']
  timeout: 28800s